#!/usr/bin/env bash

# Find the script's directory to locate call_ollama.sh
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OLLAMA_SCRIPT="$SCRIPT_DIR/call_ollama.sh"

PROJECT_NAME=$(basename "$PWD")
CURRENT_BRANCH=$(git branch --show-current)

# ── Merge commit detection ─────────────────────────────────────────────────
# When git merge is in progress, .git/MERGE_HEAD exists.
# Skip Ollama entirely — use the standard merge message as-is.
if [ -f .git/MERGE_HEAD ]; then
    MERGE_SOURCE=$(cat .git/MERGE_HEAD 2>/dev/null | cut -c1-7)
    MERGE_MSG=$(cat .git/MERGE_MSG 2>/dev/null | head -1)

    echo "Merge in progress (${MERGE_SOURCE}): ${MERGE_MSG}"
    echo "Skipping Ollama — merge commits are not generated by AI."

    git add -A
    STAGED_FILES=$(git diff --cached --name-only | tr '\n' ', ' | sed 's/, $//')
    if [ -n "$STAGED_FILES" ]; then
        echo "Staged files: $STAGED_FILES"
    fi

    echo -e "\nMerge commit message:"
    echo -e "\033[1;33m${MERGE_MSG}\033[0m\n"

    read -rp "Commit merge? (y/N) " confirm
    if [[ "$confirm" =~ ^[Yy]$ ]]; then
        git commit --no-edit

        # Update CHANGELOG if git-cliff and config are available.
        # Merge commits are filtered out via filter_unconventional = true in cliff.toml.
        if command -v git-cliff >/dev/null 2>&1 && [ -f cliff.toml ]; then
            git-cliff --config cliff.toml -o CHANGELOG.md 2>/dev/null
            if ! git diff --quiet CHANGELOG.md 2>/dev/null; then
                git add CHANGELOG.md
                git commit -m "chore: sync changelog after merge" --no-verify
                echo "CHANGELOG.md updated."
            fi
        fi

        echo "Merge committed successfully."
    else
        echo "Merge commit cancelled."
    fi
    exit 0
fi
# ──────────────────────────────────────────────────────────────────────────

echo "Staging all changes (git add -A)..."
git add -A

# Get the staged diff
DIFF=$(git diff --cached)

if [ -z "$DIFF" ]; then
    echo "❌ No changes to commit."
    exit 0
fi

# Save the diff to a temporary file
TMP_DIFF=$(mktemp)
echo "$DIFF" > "$TMP_DIFF"

STAGED_FILES=$(git diff --cached --name-only | tr '\n' ', ' | sed 's/, $//')

echo "📂 Staged files: $STAGED_FILES"
echo "🤖 Ollama is analyzing the code and writing a commit message..."

PROMPT="As a Git expert, review this git diff for the project '$PROJECT_NAME' (branch: '$CURRENT_BRANCH').
Write a concise, professional commit message in Conventional Commits format: type(scope): description.

STRICT RULES:
1. FOCUS ONLY on the provided diff. Do NOT hallucinate features or files not present in the diff.
2. If the diff shows changes to prompts or LLM logic, describe them accurately.
3. Output ONLY the message itself. No explanations, no quotes, no markdown backticks."

MESSAGE=$("$OLLAMA_SCRIPT" --role commit --prompt "$PROMPT" --context-file "$TMP_DIFF")

# Clean up Markdown backticks that small models often ignore instructions to omit
MESSAGE=$(echo "$MESSAGE" | sed '/^```/d')



rm -f "$TMP_DIFF"

if [ -z "$MESSAGE" ] || [[ "$MESSAGE" == *"Error"* ]]; then
    echo "❌ Failed to call Ollama. Error output:"
    echo "$MESSAGE"
    exit 1
fi

echo -e "\nProposed commit message:"
echo -e "\033[1;32m$MESSAGE\033[0m\n"

# Prompt the user for confirmation
read -rp "Commit with this message? (y/N) " confirm
if [[ "$confirm" =~ ^[Yy]$ ]]; then
    git commit -m "$MESSAGE"

    # Update CHANGELOG if git-cliff and config are available
    if command -v git-cliff >/dev/null 2>&1 && [ -f cliff.toml ]; then
        git-cliff --config cliff.toml -o CHANGELOG.md 2>/dev/null
        git add CHANGELOG.md 2>/dev/null || true
        git commit --amend --no-edit 2>/dev/null || true
    fi

    echo "✅ Committed successfully!"
else
    echo "🚫 Commit cancelled."
fi
